(define-constant ERR-NOT-AUTHORIZED u100)
(define-constant ERR-INSUFFICIENT-BALANCE u101)
(define-constant ERR-INVALID-AMOUNT u102)
(define-constant ERR-ACTIVITY-NOT-VERIFIED u103)
(define-constant ERR-ALREADY-STAKED u104)
(define-constant ERR-NOT-STAKED u105)
(define-constant ERR-INVALID-REWARD-RATE u106)
(define-constant ERR-INVALID-YIELD u107)
(define-constant ERR-TREASURY-EMPTY u108)
(define-constant ERR-INVALID-TIMESTAMP u109)
(define-constant ERR-INSUFFICIENT-STAKE u110)
(define-constant ERR-COOLDOWN-NOT-OVER u111)
(define-constant ERR-INVALID-RECIPIENT u112)
(define-constant ERR-CONTRACT-NOT-SET u113)
(define-constant ERR-INVALID-PARAM u114)
(define-constant ERR-MAX-STAKERS-EXCEEDED u115)
(define-constant ERR-INVALID-DURATION u116)
(define-constant ERR-REWARD-ALREADY-CLAIMED u117)
(define-constant ERR-INVALID-ACTIVITY-ID u118)
(define-constant ERR-ORACLE-NOT-VERIFIED u119)
(define-constant ERR-INVALID-TOKEN u120)

(define-data-var treasury-balance uint u1000000000)
(define-data-var reward-rate uint u10)
(define-data-var staking-yield uint u5)
(define-data-var total-staked uint u0)
(define-data-var max-stakers uint u1000)
(define-data-var cooldown-period uint u144)
(define-data-var admin principal tx-sender)
(define-data-var eco-token-contract principal 'SP000000000000000000002Q6VF78.byzantion-eco-token)
(define-data-var verification-oracle-contract (optional principal) none)

(define-map user-rewards principal uint)
(define-map user-stakes principal {amount: uint, start-time: uint, last-claim: uint})
(define-map activity-rewards uint {claimed: bool, reward-amount: uint, verifier: principal})
(define-map staker-cooldowns principal uint)
(define-map pending-claims principal uint)
(define-map reward-history principal (list 50 {timestamp: uint, amount: uint}))

(define-read-only (get-treasury-balance)
  (ok (var-get treasury-balance))
)

(define-read-only (get-reward-rate)
  (ok (var-get reward-rate))
)

(define-read-only (get-staking-yield)
  (ok (var-get staking-yield))
)

(define-read-only (get-user-reward (user principal))
  (ok (default-to u0 (map-get? user-rewards user)))
)

(define-read-only (get-user-stake (user principal))
  (ok (map-get? user-stakes user))
)

(define-read-only (get-activity-reward (activity-id uint))
  (ok (map-get? activity-rewards activity-id))
)

(define-read-only (calculate-pending-rewards (user principal))
  (let (
    (stake (default-to {amount: u0, start-time: u0, last-claim: u0} (map-get? user-stakes user)))
    (staked-amount (get amount stake))
    (last-claim (get last-claim stake))
    (time-elapsed (- block-height last-claim))
    (yield-per-block (/ (var-get staking-yield) u525600))
    (pending (* staked-amount (* yield-per-block time-elapsed)))
  )
  (ok pending))
)

(define-private (validate-amount (amount uint))
  (if (> amount u0)
    (ok true)
    (err ERR-INVALID-AMOUNT))
)

(define-private (validate-recipient (recipient principal))
  (if (not (is-eq recipient 'SP000000000000000000002Q6VF78))
    (ok true)
    (err ERR-INVALID-RECIPIENT))
)

(define-private (validate-timestamp (ts uint))
  (if (>= ts block-height)
    (ok true)
    (err ERR-INVALID-TIMESTAMP))
)

(define-private (validate-activity-id (id uint))
  (if (> id u0)
    (ok true)
    (err ERR-INVALID-ACTIVITY-ID))
)

(define-private (is-verified-activity (activity-id uint))
  (let ((oracle (unwrap! (var-get verification-oracle-contract) (err ERR-CONTRACT-NOT-SET))))
    (contract-call? oracle is-verified activity-id))
)

(define-private (transfer-eco (amount uint) (recipient principal))
  (contract-call? .eco-token transfer amount tx-sender recipient none)
)

(define-public (set-eco-token-contract (contract principal))
  (begin
    (asserts! (is-eq tx-sender (var-get admin)) (err ERR-NOT-AUTHORIZED))
    (try! (validate-recipient contract))
    (var-set eco-token-contract contract)
    (ok true))
)

(define-public (set-verification-oracle (contract principal))
  (begin
    (asserts! (is-eq tx-sender (var-get admin)) (err ERR-NOT-AUTHORIZED))
    (try! (validate-recipient contract))
    (var-set verification-oracle-contract (some contract))
    (ok true))
)

(define-public (set-reward-rate (new-rate uint))
  (begin
    (asserts! (is-eq tx-sender (var-get admin)) (err ERR-NOT-AUTHORIZED))
    (asserts! (and (> new-rate u0) (<= new-rate u100)) (err ERR-INVALID-REWARD-RATE))
    (var-set reward-rate new-rate)
    (ok true))
)

(define-public (set-staking-yield (new-yield uint))
  (begin
    (asserts! (is-eq tx-sender (var-get admin)) (err ERR-NOT-AUTHORIZED))
    (asserts! (and (> new-yield u0) (<= new-yield u20)) (err ERR-INVALID-YIELD))
    (var-set staking-yield new-yield)
    (ok true))
)

(define-public (deposit-treasury (amount uint))
  (begin
    (try! (validate-amount amount))
    (try! (transfer-eco amount (as-contract tx-sender)))
    (var-set treasury-balance (+ (var-get treasury-balance) amount))
    (ok true))
)

(define-public (claim-activity-reward (activity-id uint))
  (let (
    (reward-info (default-to {claimed: true, reward-amount: u0, verifier: tx-sender} (map-get? activity-rewards activity-id)))
    (reward-amount (get reward-amount reward-info))
  )
  (try! (validate-activity-id activity-id))
  (asserts! (is-ok (is-verified-activity activity-id)) (err ERR-ACTIVITY-NOT-VERIFIED))
  (asserts! (not (get claimed reward-info)) (err ERR-REWARD-ALREADY-CLAIMED))
  (asserts! (>= (var-get treasury-balance) reward-amount) (err ERR-TREASURY-EMPTY))
  (try! (as-contract (transfer-eco reward-amount tx-sender)))
  (var-set treasury-balance (- (var-get treasury-balance) reward-amount))
  (map-set activity-rewards activity-id {claimed: true, reward-amount: reward-amount, verifier: tx-sender})
  (map-set user-rewards tx-sender (+ (default-to u0 (map-get? user-rewards tx-sender)) reward-amount))
  (ok reward-amount))
)

(define-public (stake-eco (amount uint) (duration uint))
  (begin
    (try! (validate-amount amount))
    (asserts! (is-none (map-get? user-stakes tx-sender)) (err ERR-ALREADY-STAKED))
    (asserts! (and (> duration u0) (<= duration u525600)) (err ERR-INVALID-DURATION))
    (try! (transfer-eco amount (as-contract tx-sender)))
    (map-set user-stakes tx-sender {amount: amount, start-time: block-height, last-claim: block-height})
    (var-set total-staked (+ (var-get total-staked) amount))
    (ok true))
)

(define-public (unstake-eco)
  (let (
    (stake (unwrap! (map-get? user-stakes tx-sender) (err ERR-NOT-STAKED)))
    (amount (get amount stake))
    (cooldown-end (default-to u0 (map-get? staker-cooldowns tx-sender)))
  )
  (asserts! (>= block-height cooldown-end) (err ERR-COOLDOWN-NOT-OVER))
  (try! (claim-staking-rewards))
  (map-delete user-stakes tx-sender)
  (var-set total-staked (- (var-get total-staked) amount))
  (try! (as-contract (transfer-eco amount tx-sender)))
  (ok amount))
)

(define-public (claim-staking-rewards)
  (let (
    (stake (unwrap! (map-get? user-stakes tx-sender) (err ERR-NOT-STAKED)))
    (pending (unwrap-panic (calculate-pending-rewards tx-sender)))
  )
  (asserts! (> pending u0) (err ERR-INVALID-AMOUNT))
  (asserts! (>= (var-get treasury-balance) pending) (err ERR-TREASURY-EMPTY))
  (try! (as-contract (transfer-eco pending tx-sender)))
  (var-set treasury-balance (- (var-get treasury-balance) pending))
  (map-set user-stakes tx-sender (merge stake {last-claim: block-height}))
  (map-set user-rewards tx-sender (+ (default-to u0 (map-get? user-rewards tx-sender)) pending))
  (ok pending))
)

(define-public (initiate-unstake)
  (begin
    (asserts! (is-some (map-get? user-stakes tx-sender)) (err ERR-NOT-STAKED))
    (map-set staker-cooldowns tx-sender (+ block-height (var-get cooldown-period)))
    (ok true))
)

(define-public (distribute-bonus-rewards (recipients (list 100 principal)) (amounts (list 100 uint)))
  (begin
    (asserts! (is-eq tx-sender (var-get admin)) (err ERR-NOT-AUTHORIZED))
    (fold distribute-bonus-iter (zip recipients amounts) (ok u0))
  )
)

(define-private (distribute-bonus-iter (pair {recipient: principal, amount: uint}) (acc (response uint uint)))
  (let (
    (recipient (get recipient pair))
    (amount (get amount pair))
    (total (unwrap! acc (err ERR-INVALID-AMOUNT)))
  )
  (try! (validate-amount amount))
  (try! (validate-recipient recipient))
  (asserts! (>= (var-get treasury-balance) amount) (err ERR-TREASURY-EMPTY))
  (try! (as-contract (transfer-eco amount recipient)))
  (var-set treasury-balance (- (var-get treasury-balance) amount))
  (map-set user-rewards recipient (+ (default-to u0 (map-get? user-rewards recipient)) amount))
  (ok (+ total amount)))
)

(define-public (set-cooldown-period (new-period uint))
  (begin
    (asserts! (is-eq tx-sender (var-get admin)) (err ERR-NOT-AUTHORIZED))
    (asserts! (> new-period u0) (err ERR-INVALID-PARAM))
    (var-set cooldown-period new-period)
    (ok true))
)

(define-public (set-max-stakers (new-max uint))
  (begin
    (asserts! (is-eq tx-sender (var-get admin)) (err ERR-NOT-AUTHORIZED))
    (asserts! (> new-max u0) (err ERR-INVALID-PARAM))
    (var-set max-stakers new-max)
    (ok true))
)

(define-public (record-reward-history (user principal) (amount uint))
  (let (
    (current-history (default-to (list) (map-get? reward-history user)))
  )
  (try! (validate-amount amount))
  (map-set reward-history user (unwrap-panic (as-max-len? (append current-history {timestamp: block-height, amount: amount}) u50)))
  (ok true))
)

(define-read-only (get-reward-history (user principal))
  (ok (default-to (list) (map-get? reward-history user)))
)

(define-read-only (get-total-staked)
  (ok (var-get total-staked))
)

(define-read-only (get-pending-claim (user principal))
  (ok (default-to u0 (map-get? pending-claims user)))
)

(define-public (process-pending-claim)
  (let (
    (pending (default-to u0 (map-get? pending-claims tx-sender)))
  )
  (asserts! (> pending u0) (err ERR-INVALID-AMOUNT))
  (asserts! (>= (var-get treasury-balance) pending) (err ERR-TREASURY-EMPTY))
  (try! (as-contract (transfer-eco pending tx-sender)))
  (var-set treasury-balance (- (var-get treasury-balance) pending))
  (map-delete pending-claims tx-sender)
  (ok pending))
)